# Enable Slurm scheduler interface
slurm: True

# let Snakemake submit up to 100 jobs at the time
jobs: 100

# Print the reason why some job is executed
reason: True

# Enable Conda (required)
use-conda: True

# Enable Singularity (required)
use-singularity: True
singularity-args: "--no-home --bind /scratch" # --bind mounts specific folder in a Singularity container

# Wait up to 2 minutes for files to appear on file system
# This is to handle latency on some shared file systems
latency-wait: 120

# If a job fails, let Snakemake retry running it up to 2 times
retries: 2

default-resources:
  - "slurm_account=boulard" # this is the default account for billing of used resources
  - "slurm_partition=htc-el8" # this is the default partition jobs should be submitted to

set-resources:
  # this syntax manipulates specific resources for specific rules
  - "starTE_random:runtime=2880" # runtime
  - "star:mem_mb=128000" # memory
  - "star:slurm_partition=bigmem" # Cluster partition

# Manipulate the number of cores allocated to a specific rule
set-threads:
  - "fastqc_raw=16"
  - "star=32"
  - "starTE_random=32"
  - "starTE_multihit=32"
  - "star_genome_preparation=32"
  - "trimmomatic_pe=16"
  - "trimmomatic_se=16"