from pathlib import Path
from pprint import pprint as pp
from datetime import datetime
from urllib.parse import urlparse

import re
import pandas as pd

##########################
## PIN SNAKEMAKE VERSION
##########################

from snakemake.utils import min_version, validate

min_version("7.21.0")


################
## CONFIG FILE
################


configfile: "config/config.yaml"
validate(config, schema="schemas/config.schema.yaml")


#############################
## INCLUDE COMMON FUNCTIONS
#############################


include: "rules/common.smk"


###########################
## DEFINE PIPELINE CONTAINER
###########################


containerized: "docker://ghcr.io/boulardlab/3t-seq:feature-ui-simplifications@sha256:98add65f115f5e9e752d824b95436ef75867afd038e05ec3545cb511dc3a6b04"


#######################
## DEFINE VARIABLES
#######################


date = datetime.now()
timestamp = date.strftime("%Y-%m-%d")

data_folder = Path(config["globals"]["results_folder"])

log_folder = data_folder.joinpath("log", timestamp)
qc_folder = data_folder.joinpath("qc")
references_folder = data_folder.joinpath("references")
tmp_folder = data_folder.joinpath("tmp")
analysis_folder = data_folder.joinpath("analysis")

trim_reads_folder = data_folder.joinpath("trim")
rdata_folder = analysis_folder.joinpath("rdata")
pictures_folder = analysis_folder.joinpath("pictures")
tables_folder = analysis_folder.joinpath("tables")
notebooks_folder = analysis_folder.joinpath("notebooks")

fastqc_raw_folder = qc_folder.joinpath("fastqc-raw")
fastqc_trim_folder = qc_folder.joinpath("fastqc-trimmed")
fastqc_markdup_folder = qc_folder.joinpath("fastqc-markdup")
fastqc_star_folder = qc_folder.joinpath("star")

multiqc_folder = qc_folder.joinpath("multiqc")


alignments_folder = data_folder.joinpath("alignments")
star_folder = alignments_folder.joinpath("star")
markdup_folder = alignments_folder.joinpath("star_markdup")
starTE_folder = alignments_folder.joinpath("starTE")
salmonTE_folder = data_folder.joinpath("salmonTE")
trna_coverage_folder = data_folder.joinpath("tRNA_coverage")
deseq2_working_directory = Path(config["deseq2"]["working_directory"])
# deseq2_notebook_input_path = Path(config["deseq2"]["notebook_path"])


if "fasta_path" in config["genome"]:
    ## Generate paths for sequence data from links
    fasta_path = references_folder.joinpath(
        get_filename(config["genome"]["fasta_path"], decompress=True)
    )
else:
    fasta_path = references_folder.joinpath(config["genome"]["label"], "fasta.fa")

if "gtf_path" in config["genome"]:
    gtf_path = references_folder.joinpath(
        get_filename(config["genome"]["gtf_path"], decompress=True)
    )
else:
    gtf_path = references_folder.joinpath(config["genome"]["label"], "annotation.gtf")

rmsk_folder = references_folder.joinpath("rmsk")
tRNA_annotation_dir = references_folder.joinpath("gtrnadb")

## Get samples
libraries = config["sequencing_libraries"]

library_names_single = []
library_names_paired = []

for library in libraries:
    libname = library["name"]
    protocol = library["protocol"]
    if protocol == "pe":
        library_names_paired.append(libname)
    else:
        library_names_single.append(libname)

# Download all chromosomes if no specific chromosome was specified
if not "selected_chromosomes" in config["genome"]:
    config["genome"]["selected_chromosomes"] = None

# Default annotation_type to "ensembl" when using refgenie (label)
if "label" in config["genome"] and "annotation_type" not in config["genome"]:
    config["genome"]["annotation_type"] = "ensembl"

validate_sample_sheets()
populate_sample_registry()

####################
## ONSTART BLOCK
####################

## These folders will be create at the beginning of the pipeline
init_folders = [
    log_folder,
    trim_reads_folder,
    multiqc_folder,
    alignments_folder,
    references_folder,
    tmp_folder,
    star_folder,
    starTE_folder,
    salmonTE_folder,
    tables_folder,
    pictures_folder,
    notebooks_folder,
    fastqc_raw_folder,
]


onstart:
    import json
    from rich import print_json

    for folder in init_folders:
        mkdir(folder)

    print_json(json.dumps(config))


#############
## WORKFLOW
#############


wildcard_constraints:
    serie="|".join(library_names_single + library_names_paired),
    se_serie="|".join(library_names_single),
    pe_serie="|".join(library_names_paired),
    method="multihit|random",
    mate=r"_[MR][12](?:_sequence)?",


include: "rules/download-references.smk"
include: "rules/fastqc.smk"
include: "rules/trimming.smk"
include: "rules/star.smk"
include: "rules/deseq2.smk"
include: "rules/salmonTE.smk"
include: "rules/starTE.smk"
include: "rules/filter_bam.smk"
include: "rules/picard_markdup.smk"
include: "rules/make_bw.smk"
include: "rules/coverage_tRNA.smk"
include: "rules/multiqc.smk"


rule all:
    input:
        build_rule_all_inputs,
