from pathlib import Path
from pprint import pprint as pp
from datetime import datetime
from urllib.parse import urlparse

import re
import pandas as pd

##########################
## PIN SNAKEMAKE VERSION
##########################

from snakemake.utils import min_version, validate

min_version("7.21.0")


################
## CONFIG FILE
################


# Load and validate config
schema_path = Path(workflow.basedir) / "schemas" / "config.schema.yaml"
validate(config, schema=str(schema_path))


#############################
## INCLUDE COMMON FUNCTIONS
#############################


include: "rules/common.smk"


apply_schema_defaults(config, str(schema_path))


###########################
## DEFINE PIPELINE CONTAINER
###########################


containerized: "docker://ghcr.io/boulardlab/3t-seq:latest"


#######################
## DEFINE VARIABLES
#######################

# Date and basic folders
timestamp = datetime.now().strftime("%Y-%m-%d")
data_folder = Path(config["globals"]["results_folder"])
log_folder = data_folder / "log" / timestamp
tmp_folder = data_folder / "tmp"

# Quality Control
qc_folder = data_folder / "qc"
fastqc_raw_folder = qc_folder / "fastqc-raw"
fastqc_trim_folder = qc_folder / "fastqc-trimmed"
fastqc_markdup_folder = qc_folder / "fastqc-markdup"
fastqc_star_folder = qc_folder / "star"
multiqc_folder = qc_folder / "multiqc"

# Alignments and Analysis
alignments_folder = data_folder / "alignments"
star_folder = alignments_folder / "star"
markdup_folder = alignments_folder / "star_markdup"
starTE_folder = alignments_folder / "starTE"
salmonTE_folder = data_folder / "salmonTE"
trna_coverage_folder = data_folder / "tRNA_coverage"
trim_reads_folder = data_folder / "trim"

analysis_folder = data_folder / "analysis"
rdata_folder = analysis_folder / "rdata"
pictures_folder = analysis_folder / "pictures"
tables_folder = analysis_folder / "tables"
notebooks_folder = analysis_folder / "notebooks"

# References
references_folder = data_folder / "references"
rmsk_folder = references_folder / "rmsk"
tRNA_annotation_dir = references_folder / "gtrnadb"

genome_cfg = config["genome"]
genome_label = genome_cfg["label"]

if "fasta_path" in genome_cfg:
    fasta_path = references_folder / get_filename(genome_cfg["fasta_path"], decompress=True)
else:
    fasta_path = references_folder / genome_label / "fasta.fa"

if "gtf_path" in genome_cfg:
    gtf_path = references_folder / get_filename(genome_cfg["gtf_path"], decompress=True)
else:
    gtf_path = references_folder / genome_label / "annotation.gtf"

# Sequencing Libraries
libraries = config["sequencing_libraries"]
library_names_paired = [lib["name"] for lib in libraries if lib.get("protocol") == "pe"]
library_names_single = [lib["name"] for lib in libraries if lib.get("protocol") != "pe"]

# Defaults and validation
validate_sample_sheets()
populate_sample_registry()

####################
## ONSTART BLOCK
####################

## These folders will be create at the beginning of the pipeline
init_folders = [
    log_folder,
    trim_reads_folder,
    multiqc_folder,
    alignments_folder,
    references_folder,
    tmp_folder,
    star_folder,
    starTE_folder,
    salmonTE_folder,
    tables_folder,
    pictures_folder,
    notebooks_folder,
    fastqc_raw_folder,
]


onstart:
    import json
    from rich import print_json

    for folder in init_folders:
        mkdir(folder)

    print_json(json.dumps(config))


#############
## WORKFLOW
#############


wildcard_constraints:
    serie="|".join(library_names_single + library_names_paired),
    se_serie="|".join(library_names_single),
    pe_serie="|".join(library_names_paired),
    method="multihit|random|mimseq|standard",
    mate=r"_[MR][12](?:_sequence)?",
    trim_hash="[a-f0-9]{16}",
    align_hash="[a-f0-9]{16}",
    starte_hash="[a-f0-9]{16}",
    markdup_hash="[a-f0-9]{16}",


include: "rules/download-references.smk"
include: "rules/fastqc.smk"
include: "rules/trimming.smk"
include: "rules/star.smk"
include: "rules/deseq2.smk"
include: "rules/salmonTE.smk"
include: "rules/starTE.smk"
include: "rules/filter_bam.smk"
include: "rules/picard_markdup.smk"
include: "rules/make_bw.smk"
include: "rules/coverage_tRNA.smk"
include: "rules/multiqc.smk"


rule all:
    input:
        build_rule_all_inputs,
