name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: workflow
          snakefile: workflow/Snakefile
          args: "--configfile tests/config.yaml --lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: workflow
          snakefile: workflow/Snakefile
          args: "--configfile tests/config.yaml --use-conda --use-singularity --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"

  contanerize:
    runs-on: ubuntu-latest
    needs:
      - run-workflow
    steps:
      - name: Create container file
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: workflow
          snakefile: "workflow/Snakefile"
          task: "containerize"
