[workspace]
name = "3t-seq"
version = "0.1.0"
description = "3t-seq: a Snakemake pipeline for total RNA-seq analysis"
authors = ["Francesco Tabaro"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
snakemake = "==8.9.0"
snakefmt = ">=0.11.4"
pre-commit = ">=4.5.1"
pandas = "*"
pyyaml = "*"

[tasks]
lint = "snakemake --directory .tests/integration --configfile .tests/integration/configs/remote-references.yaml --snakefile workflow/Snakefile --lint"
format = "snakefmt workflow"
hooks = "pre-commit run --all-files"
run-test = "snakemake --directory .tests/integration --configfile .tests/integration/configs/remote-references.yaml --snakefile workflow/Snakefile -n"
