[workspace]
name = "3t-seq"
version = "0.1.0"
description = "3t-seq: a Snakemake pipeline for total RNA-seq analysis"
authors = ["Francesco Tabaro"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
snakemake = "==8.9.0"
snakefmt = ">=0.11.4"
pre-commit = ">=4.5.1"
pandas = "*"
pyyaml = "*"
mamba = "*"
conda = "*"
pytest = ">=8.1.1"

[target.linux-64.dependencies]
apptainer = ">=1.2.5"

[tasks]
lint = { cmd = "snakemake --directory .tests/integration --conda-frontend conda --workflow-profile .tests/integration/profiles/{{ profile }} --configfile .tests/integration/configs/{{ config }}.yaml --snakefile workflow/Snakefile --lint", args = [{ arg = "config", default = "remote-references", choices = ["remote-references", "local-references", "adaptive-trim"] }, { arg = "profile", default = "laptop", choices = ["laptop", "hpc"] }] }
format = "snakefmt workflow"
hooks = "pre-commit run --all-files"
dry-run = { cmd = "snakemake --directory .tests/integration --conda-frontend conda --workflow-profile .tests/integration/profiles/{{ profile }} --configfile .tests/integration/configs/{{ config }}.yaml --snakefile workflow/Snakefile -n", args = [{ arg = "config", default = "remote-references", choices = ["remote-references", "local-references", "adaptive-trim"] }, { arg = "profile", default = "laptop", choices = ["laptop", "hpc"] }] }
test = { cmd = "snakemake --directory .tests/integration --conda-frontend conda --workflow-profile .tests/integration/profiles/{{ profile }} --configfile .tests/integration/configs/{{ config }}.yaml --snakefile workflow/Snakefile", args = [{ arg = "config", default = "remote-references", choices = ["remote-references", "local-references", "adaptive-trim"] }, { arg = "profile", default = "laptop", choices = ["laptop", "hpc"] }] }