sequencing_libraries:
  - name: GSE130735
    protocol: pe
    # "sample_sheet" is a csv mapping FILENAMES without extensions to GENOTYPE
    # E.g.
    #  Name,Filename,Genotype
    #  s01,some_complicate_filename_s01,WT
    #  s02,some_complicate_filename_s02,WT
    #  s03,some_complicate_filename_s03,KO
    #  s04,some_complicate_filename_s04,KO    
    sample_sheet: resources/sample-sheet.csv
    deseq2:
      test: Wald
      variable: genotype
      reference_level: WT
  

disable_TE_analysis: false
disable_tRNA_analysis: false

globals:
  results_folder: results/

genome:
  label: mm10
  annotation_type: mgi

  # URL to GtRNAdb files
  gtrnadb_url: http://gtrnadb.ucsc.edu/genomes/eukaryota/Mmusc10/mm10-tRNAs.tar.gz

deseq2:
  working_directory: .
