
sequencing_libraries:
  - name: OLFR466_TRIM66_SmartSeq
    protocol: pe
    sample_sheet: /g/boulard/lyons/projects/olfr446_mOSN_smartSeq/data/input_data_3t_seq_pipeline/olfr446_mOSN_smartSeq_t3Pipeline_input_sampleSheet.tsv
    deseq2:
      test: Wald
      variable: cell_type
      reference_level: WT

disable_TE_analysis: false
disable_salmonTE_analysis: false
disable_tRNA_analysis: false

tRNA_quantification:
  method: "mim-tRNA-seq" # Options: "standard" or "mim-tRNA-seq"
  mimseq_params:
    max_mismatches: 0.1
    cluster_identity: 0.95
    min_cov: 10

globals:
  results_folder: /g/boulard/lyons/projects/olfr446_mOSN_smartSeq/results/00_preprocessing_alignment_3TSeq/results

genome:
  label: mm10
  annotation_type: other

  # URL to GtRNAdb files
  gtrnadb_url: http://gtrnadb.ucsc.edu/genomes/eukaryota/Hsapi38/hg38-tRNAs.tar.gz
  #gtrnadb_bed: ../../../data/references/tRNA/mm10-tRNAs.bed
