sequencing_libraries:
  - name: GSE130735-subset
    # "sample_sheet" is a csv mapping FILENAMES without extensions to GENOTYPE
    # E.g.
    #  Name,Filename,Genotype
    #  s01,some_complicate_filename_s01,WT
    #  s02,some_complicate_filename_s02,WT
    #  s03,some_complicate_filename_s03,KO
    #  s04,some_complicate_filename_s04,KO
    sample_sheet: sample-sheet.csv
    trimmomatic: "ILLUMINACLIP:$CONDA_PREFIX/share/trimmomatic/adapters/TruSeq3-PE.fa:1:15:10 SLIDINGWINDOW:8:22 MAXINFO:20:0.6 LEADING:22 TRAILING:20 MINLEN:50"
    star: "--seedSearchStartLmax 30 --outFilterMismatchNoverReadLmax 0.04 --winAnchorMultimapNmax 40"
    bamCoverage: "--binSize 10 --normalizeUsing None"
    deseq2:
      test: Wald
      variable: genotype
      reference_level: WT

disable_TE_analysis: false
disable_tRNA_analysis: false

globals:
  # <reads_folder>/<library-name> is the expected pattern
  reads_folder: .
  
  results_folder: results/
  qc_folder: results/qc
  log_folder: results/log
  references_folder: references
  tmp_folder: /tmp
  analysis_folder: results/analysis

genome:
  label: mm10
  annotation_type: mgi

  # URL for genome fasta file
  fasta_url: https://s3.embl.de/boulard/GRCm38.primary_assembly.genome.chr19.fa

  # URL for genome GTF file
  gtf_url: https://s3.embl.de/boulard/MGI.chr19.gff3

  # URL to GtRNAdb files
  gtrnadb_url: http://gtrnadb.ucsc.edu/genomes/eukaryota/Mmusc10/mm10-tRNAs.tar.gz
  #gtrnadb_bed: ../../../data/references/tRNA/mm10-tRNAs.bed

deseq2:
  working_directory: .
  variable: genotype
  test: Wald
  reference_level: WT

