sequencing_libraries:
  - name: GSE130735-subset
    protocol: pe
    # "sample_sheet" is a csv mapping FILENAMES without extensions to GENOTYPE
    # E.g.
    #  Name,Filename,Genotype
    #  s01,some_complicate_filename_s01,WT
    #  s02,some_complicate_filename_s02,WT
    #  s03,some_complicate_filename_s03,KO
    #  s04,some_complicate_filename_s04,KO    
    sample_sheet: sample-sheet.csv
    deseq2:
      test: Wald
      variable: genotype
      reference_level: WT
  

disable_TE_analysis: false
disable_salmonTE_analysis: false
disable_tRNA_analysis: false

globals:
  reads_folder: .tests/integration
  results_folder: results/

genome:
  label: mm10
  annotation_type: mgi
  # Refgenie will automatically fetch mm10 assets.

  # URL to GtRNAdb files
  gtrnadb_url: https://gtrnadb.org/genomes/eukaryota/Mmusc10/mm10-tRNAs.tar.gz
  
  # for testing purpose, focus on chr19 only
  selected_chromosomes:
    - chr19

deseq2:
  working_directory: .
  variable: genotype
  test: Wald
  reference_level: WT

