comparisons:
  - name: GSE130735-subset
    protocol: pe
    # "sample_sheet" is a csv mapping FILENAMES without extensions to GENOTYPE  
    sample_sheet: sample-sheet.csv
    trimmomatic: "ILLUMINACLIP:$CONDA_PREFIX/share/trimmomatic/adapters/TruSeq3-PE.fa:1:15:10 SLIDINGWINDOW:8:22 MAXINFO:20:0.6 LEADING:22 TRAILING:20 MINLEN:50"
    star: "--seedSearchStartLmax 30 --outFilterMismatchNoverReadLmax 0.04 --winAnchorMultimapNmax 40"
    bamCoverage: "--binSize 10 --normalizeUsing None"
    deseq2:
      test: Wald
      variable: genotype
      reference_level: WT
  

disable_TE_analysis: false
disable_salmonTE_analysis: false
disable_tRNA_analysis: false

globals:
  results_folder: results/

genome:
  label: mm10
  
  # for testing purpose, focus on chr19 only
  selected_chromosomes:
    - chr19
