name: 3t-seq test run

on:
  release:
    types: [ published ]
  pull_request:
    branches-ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: tests
          snakefile: workflow/Snakefile
          args: "--configfile .tests/config.yaml --lint"
  run-unit-tests:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Add Conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH    
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Setup snakemake
        run: |
          mamba install -c conda-forge -c bioconda snakemake=7.32.4 apptainer=1.2.5
      - name: Pytest
        run: |
          pytest .tests/unit

  run-integration-tests:
    runs-on: ubuntu-latest
    needs:
      - linting
      - formatting
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Add Conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH    
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
      - name: Setup snakemake
        run: |
          mamba install -c conda-forge -c bioconda snakemake=7.32.4 apptainer=1.2.5
      - name: Run workflow
        run: |
          ROOT=$(realpath .)
          snakemake \
          --directory .tests/integration \
          --configfile .tests/integration/config.yaml \
          --profile .tests/integration/profile \
          --snakefile workflow/Snakefile \
          --all-temp \
          --singularity-args="--bind $ROOT --bind $HOME"

