name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # run-unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #         lfs: true

  #     - name: Setup Pixi
  #       uses: prefix-dev/setup-pixi@v0.8.1
  #       with:
  #         pixi-version: v0.39.1
  #         cache: true

  #     - name: Run Pytest
  #       run: pixi run unit-test

  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.1
          cache: true

      - name: Run Integration Tests
        run: |
          ROOT=$(realpath .)
          pixi run test --config adaptive-trim --profile laptop \
          --singularity-args="--bind $ROOT --bind $HOME"
